# Generated by Django 3.2.14 on 2022-07-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issueRoom', models.CharField(max_length=20)),
                ('issueProf', models.CharField(max_length=50)),
                ('issueName', models.CharField(max_length=20)),
                ('issueTime', models.TimeField()),
            ],
        ),
    ]
