# Generated by Django 3.2.14 on 2022-07-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20220719_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='issueContent',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='community',
            name='issueName',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='community',
            name='issueProf',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='community',
            name='issueRoom',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='community',
            name='issueTime',
            field=models.TimeField(),
        ),
    ]
