# Generated by Django 4.0.6 on 2022-07-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_issue_room_delete_community'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('Email', models.CharField(max_length=20)),
                ('UserID', models.CharField(max_length=15)),
                ('UserPW', models.CharField(max_length=15)),
            ],
        ),
    ]
