# Generated by Django 4.0.6 on 2022-07-23 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='Email',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Name',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='UserID',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='UserPW',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
