# Generated by Django 4.0.6 on 2022-07-23 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_alter_userinfo_email_alter_userinfo_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='ReUserPW',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
