# Generated by Django 4.0.6 on 2022-07-24 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_userinfo_reuserpw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='Content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='Prof',
            new_name='prof',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='Room',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='Time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='ReUserPW',
            new_name='reUserPW',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='UserID',
            new_name='userID',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='UserPW',
            new_name='userPW',
        ),
        migrations.AlterField(
            model_name='room',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.userinfo'),
        ),
    ]
