# Generated by Django 3.1.3 on 2022-07-29 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_auto_20220729_1639'),
        ('userdb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
